on:
  push:
    branches: [ main ]

name: publish crate updates

jobs:
  publish_crate_updates:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1

        with:
          ref: ${{ github.event.push.before }}
          profile: minimal
          toolchain: 1.65.0
          override: true
      - name: Install cargo-smart-release
        run: cargo install cargo-smart-release

      - name: Publish updates
        run: sh ./sv2-publish.sh -e -u --no-publish --no-push --no-changelog