on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Check sv2.h file is up to date with commit
name: sv2.h Header Check

jobs:
  sv2_header_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1

        with:
          profile: minimal
          toolchain: 1.57.0
          override: true
      - name: Check sv2 header file is up to date with commit
        run: |
          echo Check sv2 header file is up to date with commit
          sh ./sv2-header-check.sh
